# fly.toml file generated for allezgo on 2021-06-30T16:29:41-04:00

app = "allezgo"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = 'allezgo-service:latest'

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8443
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 1000000
    soft_limit = 900000
    type = "connections"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
